# Generated by Django 6.0.2 on 2026-03-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='password',
            field=models.CharField(default='anjani123', max_length=15),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='status',
            field=models.CharField(default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='username',
            field=models.CharField(default='vizaymeena', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('blocked', 'blocked')], max_length=10),
        ),
    ]
