# Generated by Django 6.0.2 on 2026-03-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='password',
            field=models.CharField(default='anjani123', max_length=8),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='username',
            field=models.CharField(default='vizaymeena', max_length=20, unique=True),
        ),
    ]
