# Generated by Django 6.0.2 on 2026-03-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('blocked', 'blocked')], max_length=10),
        ),
    ]
