# Generated by Django 6.0.2 on 2026-03-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_accountholder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='password',
            field=models.CharField(default='anjani123', max_length=15),
        ),
    ]
